### ISSUE TITLE
Ghost API returns 401 Unauthorized

### ISSUE THREAD

**Issue by fuzzmz** [psychobunny/nodebb-plugin-blog-comments#11]
Looks like something changed in the Ghost API for version 0.5 because I am stuck on the "sign in to Ghost to enable the publish button." page.

The GET call to `/ghost/api/v0.1/posts/22/`returns a 401 Unauthorized, with the response `{"type":"error","message":"Please Sign In","status":"passive"}`

I guess the Authorization header isn't sent on request (see TryGhost/Ghost/issues/3177) as well as TryGhost/Ghost/issues/3748

**Comment by psychobunny** [comment]
I've just released v0.3.0 of this plugin:

* Fixed quite a few server crashes (especially when publishing)
* Compatible with NodeBB 0.6x+ and Ghost 0.5.10
* Added tags support for Ghost

Sorry for the super delay, I haven't had much chance outside of NodeBB development to dedicate to this plugin until now
