### ISSUE TITLE
Which version for NodeBB v0.4.3?

### ISSUE THREAD

**Issue by nodecode** [psychobunny/nodebb-plugin-blog-comments#14]
Which version of nodebb-plugin-blog-comments should I use for NodeBB v0.4.3? The latest version 0.1.16?

**Comment by psychobunny** [comment]
I've just released v0.3.0 of this plugin:

* Fixed quite a few server crashes (especially when publishing)
* Compatible with NodeBB 0.6x+ and Ghost 0.5.10
* Added tags support for Ghost

Sorry for the super delay, I haven't had much chance outside of NodeBB development to dedicate to this plugin until now
