### ISSUE TITLE
Wordpress - "Commenting has been disabled"

### ISSUE THREAD

**Issue by artxgroup** [psychobunny/nodebb-plugin-blog-comments#15]
When you create a post in Wordpress topic is not automatically created in the NodeB. Therefore, for all users except the administrator, it is impossible to leave a message.

"Commenting has been disabled."

**Comment by psychobunny** [comment]
> I know only, this button does not always work. Throws an error are not allowed ...

Button should be fixed in latest version + latest nodebb
