### ISSUE TITLE
Ghost post JSON changed breaking comment publish

### ISSUE THREAD

**Issue by fuzzmz** [psychobunny/nodebb-plugin-blog-comments#17]
The JSON reply to `/ghost/api/v0.1/posts/:id` has changed between v0.4.x and v0.5.x.

The new reply is `{posts: [result.toJSON()]}` versus the old one which just returned `result.toJSON()`. This means that the code for parsing the reply ([line 154 in /public/lib/embed.js](https://github.com/psychobunny/nodebb-plugin-blog-comments/blob/master/public/lib/embed.js#L154)) won't work correctly.

Also note that the actual content returned by the API call has changed, but nothing that breaks the comments plugin (at least so far).

**Comment by fczuardi** [comment]
Why is the ghost api being used at all? Just to get the title and markdown of the post?
Can't we replace this with regular DOM query selectors since the script is already running on a page that has class names for title and content? Or simply get the title only…

**Comment by fczuardi** [comment]
What I am trying to say is that the script could fallback to a non-API-dependent version while Ghost doesnt provide public access to some API calls.

**Comment by fczuardi** [comment]
the ghost fix we are waiting is https://github.com/TryGhost/Ghost/issues/4181 right? while it doesnt happen here is the super-ugly workaround I am using on embej.js (I've basically removed the ajax call):

https://gist.github.com/fczuardi/72a5103b5c1f0ba87eb3

**Comment by fuzzmz** [comment]
@fczuardi, you are right, the Ghost API is used to get the Title and Markdown of the post (and in the future things like tags and such). The title can be obtained by going through the DOM, but unfortunately the article text wouldn't be that usable due to the lack of markdown tags for formatting.

The idea of falling back to that until TryGhost/Ghost#4181 is indeed a good one.

Also, an alternative to your workaround is to modify the routes exposed by Ghost and make them public as well as this plugin to use the new routes. See [this post](https://community.nodebb.org/topic/810/nodebb-plugin-blog-comments-blog-commenting-engine-ghost-wordpress-widget/127) for my implementation.

**Comment by fczuardi** [comment]
yes @fuzzmz, patching the plugin + patching ghost is a workaround that gives better results (we get the markdown), but has the drawback of having to touch 2 projects (if you dont count changing the ghost template a patch in itself), which means remembering to re-patch if any of the two changes… nothing wrong with that, but for me just the title and link is a compromise I can live with until the bug gets fixed :)

**Comment by psychobunny** [comment]
I've just released v0.3.0 of this plugin:

* Fixed quite a few server crashes (especially when publishing)
* Compatible with NodeBB 0.6x+ and Ghost 0.5.10
* Added tags support for Ghost

Sorry for the super delay, I haven't had much chance outside of NodeBB development to dedicate to this plugin until now
