### ISSUE TITLE
Sync tags between Ghost post and NodeBB thread

### ISSUE THREAD

**Issue by fuzzmz** [psychobunny/nodebb-plugin-blog-comments#19]
Seeing as NodeBB now supports tags we can make it so the comment thread created by the plugin automagically contains the tags used in the Ghost blog post.

This will be a clean room implementation seeing as the required Ghost APIs are not yet public, but it should provide the basis on which further smaller changes might be done when the API stabilizes.

**Comment by psychobunny** [comment]
I've just released v0.3.0 of this plugin:

* Fixed quite a few server crashes (especially when publishing)
* Compatible with NodeBB 0.6x+ and Ghost 0.5.10
* Added tags support for Ghost

Sorry for the super delay, I haven't had much chance outside of NodeBB development to dedicate to this plugin until now
