### ISSUE TITLE
New Wordpress JSON API

### ISSUE THREAD

**Issue by sinofanger** [psychobunny/nodebb-plugin-blog-comments#20]
The JSON API wordpress addon recommended by this plugin (https://wordpress.org/plugins/json-api/) is rather outdated, and does not work on some blogs running WordPress 4.0+. Is this plugin compatible with the WordPress JSON API bundled with Jetpack:
http://jetpack.me/support/json-api/
I tried using the Jetpack bundled JSON API module, but it fails to pull or push comments. This plugin (https://wordpress.org/plugins/json-api/) is obsolete as of WordPress 3.9.

**Comment by michaelpfaff** [comment]
Did you ever figure this out? I think I'm running into the same issue. Running Wordpress 4.7.1 and blog-comments isn't working.
