### ISSUE TITLE
Only Administrators or members of the publishers group can publish articles

### ISSUE THREAD

**Issue by adenau** [psychobunny/nodebb-plugin-blog-comments#22]
Hi,

I'm having a few problems getting Ghost/Nodebb integration to work. To make things more complicated, I'm running both software on two different hosts.

I've installed the latest version of Ghost (0.5.3), NodeBB (0.6.0) and the integration plugin from npm. Both sites are proxies through NGINX. I login using my administrator account in both ghost in nodebb. When I look at an article, I can need the Publish this Article to NodeBB button. However, if I press it, I receive the following message : 

{"error":"Only Administrators or members of the publishers group can publish articles"

I can confirmed that I am properly logged in, as I can just go back to the root of NodeBB and the administration menu. I've confirmed that I am using the proper categorie in my plugin configuration, and that administrator has the proper rights to post to that category.

I've integrated in Ghost using the following code 

```
<a id="nodebb/comments"></a>
<script type="text/javascript">
var nodeBBURL = 'http://forums.technodabbler.com',
    articleID = '{{post.id}}';

(function() {
var nbb = document.createElement('script'); nbb.type = 'text/javascript'; nbb.as
ync = true;
nbb.src = nodeBBURL + '/plugins/nodebb-plugin-blog-comments/lib/embed.min.js';
(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body
')[0]).appendChild(nbb);
})();
</script>
<noscript>Please enable JavaScript to view comments</noscript>
```

Any ideas?

**Comment by fczuardi** [comment]
This bug should be reopened since it is not fixed yet. Are discussions going on #17?

**Comment by psychobunny** [comment]
Sorry about causing you grief, but yeah, I am waiting on one of Ghost's issues to be closed before I put time into this. In #17 there is a mention of a hotfix, which isn't ideal but works. Our blog is still using an older version of Ghost as well: https://blog.nodebb.org/nodebb-v0-5-0-released/
