### ISSUE TITLE
Compatability with PencilBlue CMS

### ISSUE THREAD

**Issue by misbahneo** [psychobunny/nodebb-plugin-blog-comments#24]
Hi there

was just wondering if you had any plans to try and make this compatible with the  pencilblue cms

or 

is it already compatible and im just being stupid?

**Comment by psychobunny** [comment]
I haven't gotten the chance to play with pencilblue, it's definitely not on my todo list - but if there's some significant demand I'll have a look. It's probably possible that with minor changes you could get it to work, no idea though. I'm assuming it uses markdown like Ghost so it will be easier to implement

**Comment by psychobunny** [comment]
Closed due to lack of interest, I'd still love to accept a PR though. This might be superseded in my next planned refactor that will take any ID and make it compatible with any CMS
