### ISSUE TITLE
NodeBB CSRF Middleware

### ISSUE THREAD

**Issue by norganna** [psychobunny/nodebb-plugin-blog-comments#31]
Hi,

I needed to make some changes to get the CSRF token working with the middleware in the current version of NodeBB. Thought you'd like to know.

Changes were pretty basic in library.js:

    token: res.locals.csrf_token,
becomes:

    token: req.csrfToken(),

and:

    app.get('/comments/get/:id/:pagination?', Comments.getCommentData);
becomes:

    app.get('/comments/get/:id/:pagination?', middleware.applyCSRF, Comments.getCommentData);

**Comment by psychobunny** [comment]
Thanks!
