### ISSUE TITLE
Is the plugin going to be compatible with nodebb 0.9?

### ISSUE THREAD

**Issue by doppioslash** [psychobunny/nodebb-plugin-blog-comments#33]
As in the subject, sorry if it's already in the works.
Just wondering whether I should downgrade back or wait.

**Comment by nwgat** [comment]
seems buggy, i get issues with CORS http://enable-cors.org/ on nodebb 0.9

**Comment by doppioslash** [comment]
any news on this?

**Comment by psychobunny** [comment]
This is compatible with the latest NodeBB as of 0.4.3
