### ISSUE TITLE
XMLHttpRequest denied access

### ISSUE THREAD

**Issue by peterdemartini** [psychobunny/nodebb-plugin-blog-comments#4]
I get the following error after following the instructions for installation. This error appears when viewing the ghost blog entry.

```
XMLHttpRequest cannot load http://forum.[domain].com/comments/get/2/0. The 'Access-Control-Allow-Origin' header contains the invalid value 'undefined'. Origin 'http://blog.[domain].com' is therefore not allowed access. 
```

I see in the library.js you are setting the "Access-Control-Allow-Origin" headers so I am not entirely sure why it isn't working. Maybe the `meta.config['blog-comments:url']` isn't being set properly.

Any help would be much appreciated.

**Comment by akoSalman** [comment]
@psychobunny I have the same error and could not resolve it. can you help me please
