### ISSUE TITLE
Jquery error breaking page with this on wordpress

### ISSUE THREAD

**Issue by Fma965** [psychobunny/nodebb-plugin-blog-comments#46]
Hi, when the id was "nodebb/comments" my jquery/scripts was making the page not load and giving me a undefined error in console, now i know this is specifc to my site but my suggestion is to redo it as #nodebb-comments instead of #nodebb/comments. i manually changed all refferences to this and now it works fine. i don't even know if a / in a id tag is valid is it?

Hope you consider this change. Thanks.

**Comment by psychobunny** [comment]
I'm happy to accept that as a PR if you wouldn't mind. Makes sense to me, not sure what I was thinking

**Comment by Fma965** [comment]
I'll see what I can do, all I literally did was replace all references of
nodebb/comments to nodebb-comments. If I get time I'll clone and send you a
pr

**Comment by psychobunny** [comment]
Thanks!
