### ISSUE TITLE
User images giving 404

### ISSUE THREAD

**Issue by giantkingsquid** [psychobunny/nodebb-plugin-blog-comments#50]
Hi,

My nodebb is in a subdirectory, `https://domain.org/forum`. For whatever reason the user images next to blog comments in ghost are going 404 as it appears that the plugin is putting too many "forums" in.

```
Failed to load resource: the server responded with a status of 404 (Not Found) https://domain.org/forum/forum/uploads/profile/2-profileimg.png
```

Any ideas on how to fix this? Everything else appears to be working and I'm loving the NodeBB/Ghost combo.

**Comment by philskents** [comment]
Hi,

I need a little more info on your setup. I understand your platform is Ghost, do you have anything proxying (nginx etc)?

**Comment by giantkingsquid** [comment]
Hi,

Yes I have Nginx proxying both Ghost and NodeBB.
