### ISSUE TITLE
forked commnets2 does not work with NodeBB v1.4.1. and ghost 0.11.3

### ISSUE THREAD

**Issue by xenofobic** [psychobunny/nodebb-plugin-blog-comments#63]
take a look at https://github.com/revir/nodebb-plugin-blog-comments2
is it possible make it work with NodeBB v1.4.1. and ghost 0.11.3
in my setup only the button "publish this article" works well
but login and registration button does not show and also the comments count show zero even there are comments in nodeBB
thanks

**Comment by psychobunny** [comment]
sorry about this, but I don't really have the time to debug forks of this plugin. If master works for you, then maybe you might want to carefully have another look at the modifications you've made?

if master doesn't work for you please feel free to open a new issue. Thanks :)

**Comment by xenofobic** [comment]
your master does not work :( 
therefore I tried that fork
