### ISSUE TITLE
Capcha is not working

### ISSUE THREAD

**Issue by henrikekblad** [psychobunny/nodebb-plugin-blog-comments#65]
The cactcha is not working when trying to register a new account through this plugin (including on Nodebb.org). 

(We see the same behaviour on mysensors.org after upgrading NodeBB to latest)

Trying to grasp how the captcha javascript get initialised and loaded but fail.. Do you have any quick fix for this @psychobunny?

**Comment by psychobunny** [comment]
@henrikekblad sorry for the late reply. I'm not seeing this behavior on community.nodebb.org -- seems to be fine with me. Could you let me know if you can still reproduce on latest? I'm planning on revamping this plugin a little bit and fixing up all these issues soon. Thanks!
