### ISSUE TITLE
XHR 502 error - no comments displaying

### ISSUE THREAD

**Issue by Joykiller** [psychobunny/nodebb-plugin-blog-comments#69]
![screenshot from 2017-07-31 23-27-53](https://user-images.githubusercontent.com/13190088/28812180-52a9313a-7648-11e7-9f75-94291cc77c5e.png)

**Comment by firstred** [comment]
Looks like the `nodebb-plugin-ns-awards-next` and `nodebb-plugin-ns-points` plugins are causing trouble. I managed to restore the blog comments functionality by disabling these two plugins.

**Comment by Joykiller** [comment]
I'll give her a go. thanks for tip.

**Comment by barisusakli** [comment]
What is the complete articleID? Any errors in nodebb or ghost logs?

**Comment by Joykiller** [comment]
@firstred thanks for tip it worked.
