### ISSUE TITLE
Refactor plugin to not require a unique id from each blog

### ISSUE THREAD

**Issue by julianlam** [psychobunny/nodebb-plugin-blog-comments#8]
Use URLs as the canonical identifier

Though URLs do change, so perhaps also build in the functionality to do a "mapping", so if `http://siteA.com/blog` changes to `https://blog.siteB.com`, the topics don't lose their reference to the downstream post...

**Comment by psychobunny** [comment]
I've just released v0.3.0 of this plugin:

* Fixed quite a few server crashes (especially when publishing)
* Compatible with NodeBB 0.6x+ and Ghost 0.5.10
* Added tags support for Ghost

Sorry for the super delay, I haven't had much chance outside of NodeBB development to dedicate to this plugin until now

**Comment by psychobunny** [comment]
haha woops, it's julian.
