### ISSUE TITLE
Blog comments not showing comments (with fix)

### ISSUE THREAD

**Issue by djensen47** [psychobunny/nodebb-plugin-blog-comments#81]
Even on the NodeBB blog, the comments are not appearing on the blog post. The only thing that loads is the comment box.

It's because of this line:
https://github.com/revir/nodebb-plugin-blog-comments2/blob/master/library.js#L97

It always resolved to false because the value in the database is 0 (not `false`)

The fix is super simple:

change
```
return post.deleted === false;
```
to
```
return !post.deleted;
```

**Comment by djensen47** [comment]
@barisusakli I'm mentioning you since I'm not sure if @psychobunny is still maintaining this or not.

**Comment by psychobunny** [comment]
Thanks, I see the PR is on the blog-comments2 version of the plugin, did you want to PR it here as well or should I make the change?

**Comment by djensen47** [comment]
Oops. Yeah, I'll take care of that in a bit.
